### PR TITLE
Filtering

### PR DESCRIPTION
**Pull request by jonmifsud**
This introducing Order Filtering where you can have specific orders for filtered views. These orders can be output to the frontend by having a "Matching" datasource filter on the same parameter combination. 

If the filters within the publish filtering and the datasource are not an exact match, the ordering will not work as expected. Trying to see what is the best way to approach this to make further improvements.

This change should be compatible with 2.6.x, possibly lower.

### CODE REVIEW

**Comment by jonmifsud** [comment]
@nitriques submitted the PR. I think it's still needs a bit more work to resolve the issue mentioned in the PR. I have also noticed a [similar issue](https://github.com/symphonycms/symphony-2/issues/2331) though I didn't get a definitive reply from @brendo. In my opinion in the case of associations I should be saving the entry ID, and filtering would theoretically do the same thing to the pre-populated fields mentioned within [that issue](https://github.com/symphonycms/symphony-2/issues/2331).

**Comment by nitriques** [comment]
@jonmifsud I will have the time to check this out next week. Right now, I have to do non-OSS stuff :(

**Comment by jonmifsud** [comment]
@nilshoerrmann / @nitriques just decoupled this from the core changes. So it should work out of the box on 2.6. As you'll note I'm using `Symphony.Context.get('env').pagination` etc. the idea is that eventually these will be replaced by the core versions if they are provided and it would keep backwards compatibility. Eventually just dropping off the relevant parts from the `addComponents` function.

**Comment by nitriques** [comment]
Great ! Do you need me to do anything ? (except testing)

**Comment by nilshoerrmann** [comment]
This seems to work like a charm. Thanks a lot!

**Comment by nilshoerrmann** [comment]
I merged this manually so we don't loose the changes in `integration`.

**Comment by jonmifsud** [comment]
@nilshoerrmann no problem :) would have done it if asked to. 

Let me know if you encounter anything unexpected whilst using this, and I'll be happy to make changes.

**Comment by nilshoerrmann** [comment]
It's really working smooth so far. Your changes have been a huge help so far.

**Pull request closed without merging**
