### PR TITLE
Version 2.3.0

### PR DESCRIPTION
**Pull request by nitriques**
This PR is the 2.3.0 release of this extensions.

If no one reviews this in the 7 days, I'll release it.

All it does is merging integration into master. I can confirm it works on 2.6.3

### CODE REVIEW

**Comment by nitriques** [comment]
cc @jonmifsud

**Comment by jonmifsud** [comment]
@nitriques are you still waiting on feedback from myself on this? Or are we waiting to solve the other issue first.

**Comment by nitriques** [comment]
>  Or are we waiting to solve the other issue first.

I think we are waiting for the other not fixed issue, i.e. #69

**Comment by nitriques** [comment]
This needed release bad...

**Pull request merged**
