### PR TITLE
fix order xml value

### PR DESCRIPTION
**Pull request by jonmifsud**
@nitriques / @animaux can you please check to see if these changes make any difference to the ordering on your end. Please note that this could have some adverse impact in the sense if ordering was coming out incorrectly before it might not necessarily fix it, but might put the XML value with the same order as it appeared in the XML order/sorting. I can confirm values now appear consistent at least when filters are applied. Suggestion is to try on a demo/local copy for feedback.

### CODE REVIEW

**Comment by animaux** [comment]
Thanks! In a quick test this changed from the order it had before:

`4, 3, 5`

to

`5, 3, 4`

Do I need to resave anything?

**Comment by animaux** [comment]
Some reordering and then resaving the DS did not result in any further changes.

**Comment by nitriques** [comment]
Still a valid change... ALWAYS sanitize ALL inputs.

**Comment by jonmifsud** [comment]
@nitriques I've made some changes, a couple of small bug fixes, and more importantly a documentation update. Can you check out if the example use case makes sense? Otherwise you can merge into your 2.3.0 release (review) and go ahead.

**Comment by nitriques** [comment]
@jonmifsud I am missing free time these time, will try to test ASAP. Thanks.

**Comment by jonmifsud** [comment]
No problem I understand pretty much the same here.

**Pull request merged**
