### PR TITLE
Fixing some issues with Filtering

### PR DESCRIPTION
**Pull request by nitriques**
This one would be better reviewed on a commit by commit basis since, I've added separated all operations into commits.

cc @jonmifsud, as we discussed on Gitter.

### CODE REVIEW

**Comment by jurajkapsz** [comment]
Ok, I've tried out this PR (downloaded patch-4) the usual ways (applying sort, creating entries, filtering in ds etc., except its Filtering Ordering, 'cause I don't understand this feature yet heh :), no errors.

**Comment by jonmifsud** [comment]
Great I'll test out the filtering as soon as I get some time.

**Comment by nitriques** [comment]
Thanks @jurajkapsz !

**Comment by jonmifsud** [comment]
@nitriques seems fine to me with filtered entries. Anything in particular I should be 'testing'? I've gone into a filtered section, sort order comes up good, drag and drop will re-sort with the correct indices.

**Comment by nitriques** [comment]
Great!

> Anything in particular I should be 'testing'

You're new features, but it seems like you already did that. I'll merge a couple of other thing into integration, would be cool if you would test it.

**Pull request merged**
